version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    
  api:
    build: .
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      MONGOURI: mongodb://mongodb:27017/twitter
    depends_on:
      - mongodb

volumes:
  mongodb:
